fos_comment_comment_create:
    pattern:        /new
    defaults:       { _controller: FOSCommentBundle:Comment:create }
    requirements:   { _method: "post" }

fos_comment_thread_show_feed:
    pattern:        /{identifier}.xml
    defaults:       { _controller: FOSCommentBundle:Thread:showFeed, _format: xml }

fos_comment_comment_loadmore:
    pattern:        /subtree/{commentId}
    defaults:       { _controller: FOSCommentBundle:Comment:subtree }

fos_comment_vote_add_up:
    pattern:        /vote/{commentId}/up
    defaults:
        _controller:  FOSCommentBundle:Vote:add
        value:        1

fos_comment_vote_add_down:
    pattern:        /vote/{commentId}/down
    defaults:
        _controller:  FOSCommentBundle:Vote:add
        value:        -1

fos_comment_vote_list:
    pattern:        /votes/{commentId}
    defaults:       { _controller: FOSCommentBundle:Vote:list }
