language: php
dist: precise

php:
    - 5.6
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.0
          env: SYMFONY_VERSION='2.7.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.8.*'
    fast_finish: true

install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer update --no-interaction $COMPOSER_FLAGS

script:
    - composer validate --no-check-lock --strict
    - ./vendor/bin/phpunit --coverage-text --colors
